<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>World Waste War - 404</title>
    <link rel="preload" href="./assets/fonts/UpheavalTT-BRK-.woff2" as="font" type="font/woff2" crossorigin>
    <link rel="icon" href="./assets/medias/icons/www_icon.png" type="image/x-icon"/>
    <link rel="stylesheet" href="./assets/css/style.css" type="text/css" />
</head>
<body>
    <div class="error-404">
        <h1>Woops, are you lost ?</h1>
        <p>Try to go <a href="https://quentinbruyere.sites.3wa.io/Soutenance/Projet_Final/">here</a> !</p>
        <p class="errorMsg">404 error</p>
    </div>
</body>
</html>