<div class="about">
    <h1>About</h1>
    <article class="introduction">
        <p>World Waste War is a end coding training project. It's a 2D pixel styled, stage leveling game.</p>
        <p>The concept of the game is quite simple. You have to kill all the ennemies of the stage to go to the next one. Ennemies have a chance to drop items, weapons or health potions. Some stages may have treasure chests with same loot in it.</p>
    </article>
    <article class="storyTelling">
        <p>We are in 2154. This is the apocalypse. Humans have been overwhelmed by their waste.</p>
        <p>In 2151, a Japanese laboratory got an accident and leak some chemicals in the ocean. After that, waste became alive for an unknown reason. We studied them and learned them the human language. Because they became a new specie of living being and because the laboratory was from Japan, we nammed them DETORIS.</p>
        <p>Studies and talking prove us that they were consciousfull of their existence. Firstly, Humans were surprised and gave to DETORIS a bit of interest. But quickly, Humans forgot about them and everything came back to the past like nothing ever happened. DETORIS were rejected by their disgusting nature and looking.</p>
        <p>DETORIS, rejected from the society, just tried to live set backed of it. Their knowledge and cleverness brought them to build well developped cities and technologies. After some months, the DETORIS began to think about the world around them and their reason to live. They quicly came to the conclusion that Humans were destroying their own home planet.</p>
        <p>They came back in big cities to share the message and warn population. Talking to politicians, organizations, even making demonstrations were not effective as expected... A little part of humans understood the situation but everyone else were blinded by their XXIIth century comfort...</p>
        <p>In 2153, after years and months of hard tryings in vain, DETORIS decided to declare war to ALL Humans.</p>
        <p>Humans took it as a joke... But they forgot DETORIS were superior in number.. WAY MORE !</p>
    </article>
    <article class="gameIntro">
        <p>You are an inhabitant of Raz-Campagn, small town where exchanges and local production is a must since 2060.</p>
        <p>DETORIS are coming to town and don't care about your small eco-friendly village, they want all humans to be DEAD.</p>
        <p>Talking is no longer an option, take your weapons and fight them until you reach their chief to convince him to retreat !</p>
    </article>
</div>







<!--<p>C'est l'apocalypse (évidemment)
L'Homme à été submergé par ses déchets en tout genre et suite à un fuite d'un laboratoire les déchets se sont animés.
Au début, le monde était tourné vers cette nouvelle espèce d'être vivant à part entière. Nous les avons étudiés, et à force de cotoyer les humains, ils ont été apte à parler notre langue et communiquer avec nous. 
Nous les avons bâtisés les Detoris (provenant du japonais, lieu de l'accident chimique)
Nous avons constaté que les Detoris étaient tous doté d'une conscience, ce qui à fait peur à tout le monde dans un premier temps. Les déchets nouvellement crées chaque jours n'étaient pas dotés de cette conscience donc l'humanité s'en fichait et continua son mode de consommation comme si de rien n'était.
En parrallèle, les Detoris étant conscient du monde qui les entoure, se rendirent compte du crime que les humains étaient en train de faire subir à leur propre planète. Ils ont alors essayé d'avertir la population et de faire prendre conscience de la catastrophe qui était en train de se produire. Personne ne les écouta, l'humanité étant plongée depuis des décénnies dans un confort technologique qui les aveuglait année après année..

Les Detoris, déterminé à sauver la planète qui les a vu naître, ont alors déclaré la guerre à l'humanité entière. Cette déclaration fu prise à la rigolade.. Mais ce que les humains avaient oubliés c'est que les Detoris étaient nombreux.. BEAUCOUP PLUS nombreux qu'eux !


Vous incarnez un habitant de Raz-campagn, petit village qui prône l'échange, la production et le commerce local depuis 2036. Problème, les Detoris arrivent à votre village sans savoir tout cela et ils sont déterminé à tout raser sur leur passage ! Ils sont dans une rage telle que la communication ne se fait plus que par des armes.. Armez-vous, combattez-les jusqu'à atteindre leur chef pour lui faire entendre raison sur votre village !</p>-->