<div class="account">
    <h1>ACCOUNT</h1>
    <form method="POST" class="account_form" action="https://quentinbruyere.sites.3wa.io/Soutenance/Projet_Final/account-update">
        <label for="username">Username</label>
        <input class="account_form_username" type="text" name="accountUsername" value='<?= $_SESSION["username"] ?>' disabled/>
        <label for="password">Password</label>
        <input class="account_form_password" type="password" name="accountPassword" disabled/>
        <input class="account_form_submit" type="submit" value="Save Changes" disabled/>
    </form>
    <button class="account_editButton">EDIT</button>
    <a href="https://quentinbruyere.sites.3wa.io/Soutenance/Projet_Final/disconnect" title="Disconnect">Disconnect</a>
    <form method="POST" class="deleteAccount_form" action="https://quentinbruyere.sites.3wa.io/Soutenance/Projet_Final/account-delete">
        <label>Do you want to delete your account ?</label>
        <input type="radio" name="deleteAccount--confirm" required>
        <label for="deleteAccount--confirm">Yes ?</label>
        <input class="deleteAccount_form_submit" type="submit" value="Delete my account">
    </form>
</div>
<script type="text/javascript" src="./assets/javascript/modules/accountEditor.js"></script>