<div class="authentication">
    <h1>Authentication</h1>
    <div class="signInFormCard">
        <h2>Welcome back</h2>
        <button class="signInForm__displayBtn authentication__form__displayBtn--hidden">
            <span>Sign In</span>
        </button>
        <div class="signInCurtain">
            <?php 
            /*var_dump($_SESSION);
            var_dump($_POST);*/
            ?>
            <form method="POST" class="signInForm" action="https://quentinbruyere.sites.3wa.io/Soutenance/Projet_Final/sign-in">
                <?php
                
                /*if(isset($_SESSION["username"]) || isset($_SESSION["password"])){
                    if(!$_SESSION["username"] || !$_SESSION["password"]){
                        echo '<p class="red">Wrong Username or Password</p>';
                    }
                }*/
                
                ?>
                <label for="username">Username</label>
                <input type="text" name="username" class="signInUsername <?php 
                
                //if the username is false show the username input as wrong
                /*if(isset($_SESSION["username"])) {
                    if(!$_SESSION["username"]) {
                        echo "inputError";
                        unset($_SESSION["username"]);
                    }
                }*/
                
                ?>" 
                <?php
                
                //if the user tried to connect, save its username in the username input
                /*if(isset($_SESSION["username"])){
                    echo 'value="' . $_SESSION["username"] . '"';
                    unset($_SESSION["username"]);
                }*/
                
                ?>/>
                <?php //var_dump($_SESSION); ?>
                <label for="password">Password</label>
                <input type="password" name="password" class="signInPassword <?php
                
                //if the password is false show the username input as wrong
                /*if(isset($_SESSION["password"])) {
                    if(!$_SESSION["password"]) {
                        echo "inputError";
                        unset($_SESSION["password"]);
                    }
                }*/
                
                ?>"/>
                <input type="submit" value="Sign In" class="signInButton"/>
            </form>
        </div>
    </div>
    <div class="signUpFormCard">
        <h2>New Player ?</h2>
        <button class="signUpForm__displayBtn">
            <span>Sign Up</span>
        </button>
        <div class="signUpCurtain authentication__form--hidden">
            
            <form method="POST" class="signUpForm" action="https://quentinbruyere.sites.3wa.io/Soutenance/Projet_Final/sign-up">
                <label for="username">Username</label>
                <input required type="text" name="signUpUsername" class="signUpUsername <?php
                //if the email is false show the username input as wrong
                /*if(isset($_SESSION["signUpUsername"])) {
                    if(!$_SESSION["signUpUsername"]) {
                        echo "inputError";
                        unset($_SESSION["signUpUsername"]);
                    }
                }*/
                ?>"/>
                <label for="email">Email</label>
                <input required type="email" name="signUpEmail" class="signUpEmail <?php
                //if the email is false show the username input as wrong
                /*if(isset($_SESSION["signUpEmail"])) {
                    if(!$_SESSION["signUpEmail"]) {
                        echo "inputError";
                        unset($_SESSION["signUpEmail"]);
                    }
                }*/
                ?>"/>
                <label for="password">Password</label>
                <input required type="password" name="signUpPassword" class="signUpPassword <?php
                //if the password is false show the username input as wrong
                /*if(isset($_SESSION["signUpPassword"])) {
                    if(!$_SESSION["signUpPassword"]) {
                        echo "inputError";
                        unset($_SESSION["signUpPassword"]);
                    }
                }*/
                ?>"/>
                <input type="submit" value="Sign Up" class="signUpButton"/>
            </form>
            
            <?php
                /*$signUpController = new AuthenticateController();
                $signUpController->checkSignUpFields();*/
            ?>
        </div>
    </div>
</div>
<script type="text/javascript" src="./assets/javascript/modules/authenticationDisplay.js"></script>


