<div class="codex">
    <h1>CODEX</h1>
    <section class="weaponsList">
        <h2>Weapons</h2>
        <card class="weaponsList__item__1">
            <div class="weaponsList__item__1__img">
                <img src="./assets/medias/imgs/hero-pixel.png" alt="Heroe"/>
            </div>
            <div class="weaponsList__item__1__text">
                <h3>Weapon title</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo, labore, fugiat odit recusandae quisquam aperiam ipsum ducimus mollitia natus. Quia, laborum, blanditiis possimus officiis maxime similique dignissimos excepturi tenetur alias!</p>
            </div>
        </card>
        <card class="weaponsList__item__1">
            <div class="weaponsList__item__1__img">
                <img src="./assets/medias/imgs/hero-pixel.png" alt="Heroe"/>
            </div>
            <div class="weaponsList__item__1__text">
                <h3>Weapon title</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo, labore, fugiat odit recusandae quisquam aperiam ipsum ducimus mollitia natus. Quia, laborum, blanditiis possimus officiis maxime similique dignissimos excepturi tenetur alias!</p>
            </div>
        </card>
    </section>
    <section class="itemsList">
        <h2>Items</h2>
        <card class="itemsList__item__1">
            <div class="itemsList__item__1__img">
                <img src="./assets/medias/imgs/hero-pixel.png" alt="Heroe"/>
            </div>
            <div class="itemsList__item__1__text">
                <h3>Item title</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo, labore, fugiat odit recusandae quisquam aperiam ipsum ducimus mollitia natus. Quia, laborum, blanditiis possimus officiis maxime similique dignissimos excepturi tenetur alias!</p>
            </div>
        </card>
        <card class="itemsList__item__1">
            <div class="itemsList__item__1__img">
                <img src="./assets/medias/imgs/hero-pixel.png" alt="Heroe"/>
            </div>
            <div class="itemsList__item__1__text">
                <h3>Item title</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo, labore, fugiat odit recusandae quisquam aperiam ipsum ducimus mollitia natus. Quia, laborum, blanditiis possimus officiis maxime similique dignissimos excepturi tenetur alias!</p>
            </div>
        </card>
    </section>
</div>