<div class="contact">
    <h1>CONTACT</h1>
    <!-- 
    
    I searched for solutions for sending mails but couldn't find a simple one
    to install. I could send fake mails by send them to the DB but I thought it was
    a non realistic solution.
    
    -->
    <form method="POST" class="contactForm" action="https://quentinbruyere.sites.3wa.io/Soutenance/Projet_Final/send-email">
        <label for="email">Your Email</label>
        <input type="email" name="email" class="contactEmail"/>
        <label for="subject">Subject</label>
        <input type="text" name="subject" class="contactSubject"/>
        <label for="message">Message</label>
        <textarea name="message"></textarea>
        <input type="submit" value="Send" class="contactBtn"/>
    </form>
</div>