<div class="game">
    <canvas class ='stageBackground' width='400' height='400'></canvas>
    <div class='pad'>
        <div class='arrowLeft'>Left</div>
        <div class='arrowUp'>Up</div>
        <div class='arrowRight'>Right</div>
        <div class='arrowDown'>Down</div>
    </div>
    <button class="saveButton">Save</button>
    <a href="https://quentinbruyere.sites.3wa.io/Soutenance/Projet_Final/" title="Home">HOME</a>
    <a href="https://quentinbruyere.sites.3wa.io/Soutenance/Projet_Final/codex" title="Codex">CODEX</a>
</div>
<script type="module" src="./play/script.js"></script>