<div class="game">
    <canvas class ='stageBackground' width='400' height='400'></canvas>
    <div class="controls">
        <div class='pad'>
            <div class='arrowLeft'></div>
            <div class='arrowUp'></div>
            <div class='arrowRight'></div>
            <div class='arrowDown'></div>
        </div>
    </div>
    <button class="saveButton">Save</button>
</div>
<script type="module" src="./play/script.js"></script>