<card class="welcomeCard">
    <div class="welcomeCard_background"></div>
    <div class="welcomeCard__text">
        <h1>World Waste War</h1>
        <div class="welcomeCard__text__playBtn">
            <a href="https://quentinbruyere.sites.3wa.io/Soutenance/Projet_Final/<?php 
            if(isset($_SESSION["connected"])){
                if($_SESSION["connected"]){
                    echo "the-game";
                }else{
                    echo "authenticate";
                }
            }else{
                echo "authenticate";
            }
            ?>" title="Play for free">PLAY FOR FREE</a>
        </div>
    </div>
</card>
<article class="introduce">
    <card class="introduce__1">
        <p>Play the Hero of your village</p>
        <img src="./assets/medias/imgs/hero-pixel.png" alt="Heroe">
    </card>
    <card class="introduce__2">
        <img src="./assets/medias/imgs/garbage-pixel.png" alt="Detoris">
        <p>Fight the Detoris</p>
    </card>
    <card class="introduce__3">
        <img src="./assets/medias/imgs/victoryman-pixel.png" alt="Victory Man">
        <p>Until you reach their chief and save your village</p>
    </card>
</article>