<?php
    // require "./managers/user_manager.php";

    // $userManager = new UserManager;
    // $argonautList = $userManager -> getArgonauts();
    // if(isset($_POST)){
    //     var_dump($_POST);
    // }else{
    //     echo "POST non défini";
    // }
    
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WCS - TEST - from scratch - WAMP</title>
    <link rel="stylesheet" href="./assets/css/style.css">
</head>
<body>
    <header>
        <h1>
            <img src="https://www.wildcodeschool.com/assets/logo_main-e4f3f744c8e717f1b7df3858dce55a86c63d4766d5d9a7f454250145f097c2fe.png" alt="Wild Code School logo" />
            Les Argonautes
        </h1>
    </header>
    <!-- Main section -->
    <main>

        <!-- New member form -->
        <h2>Ajouter un(e) Argonaute</h2>
        <form method="POST" class="new-member-form" action="http://wcstest/register">
            <label for="name">Nom de l&apos;Argonaute</label>
            <input id="name" name="name" type="text" placeholder="Charalampos" />
            <button type="submit">Envoyer</button>
        </form>
        
        <!-- Member list -->
        <h2>Membres de l'équipage</h2>
        <section class="member-list">
            <?php 
                $userController = new UserController;
                $argonautList = $userController -> getArgonauts();

                if(isset($argonautList)){
                    foreach($argonautList as $argonaut){
                        echo "<div class='member-item'>" . $argonaut["name"] . "</div>";
                    }
                }
            ?>
        </section>
    </main>
    
    <footer>
        <p>Réalisé par Jason en Anthestérion de l'an 515 avant JC</p>
    </footer>
    <script type="module" src="script.js"></script>
</body>
</html>