<?php

if(!isset($_SESSION)){
    session_start();
}

?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>World Waste War</title>
    <link rel="preload" href="./assets/fonts/UpheavalTT-BRK-.woff2" as="font" type="font/woff2" crossorigin>
    <link rel="icon" href="./assets/medias/icons/www_icon.png" type="image/x-icon"/>
    <link rel="stylesheet" href="./assets/css/style.css" type="text/css" />
</head>
<body>
    <header>
        <div class="menu__btn">
            <div class="menu__btn__bar"></div>
        </div>
        <div class="menu__sideModal">
            <nav>
                <ul>
                    <li class="menu__sideModal__home"><a href="https://quentinbruyere.sites.3wa.io/Soutenance/Projet_Final/">Home</a></li>
                    <li class="menu__sideModal__game">
                        <a href="https://quentinbruyere.sites.3wa.io/Soutenance/Projet_Final/<?php 
                            if(isset($_SESSION["connected"])){
                                if($_SESSION["connected"]){
                                    echo "the-game";
                                }else{
                                    echo "authenticate";
                                }
                            }else{
                                echo "authenticate";
                            }
                            ?>" title="Play for free">Game</a>
                    </li>
                    <li class="menu__sideModal__codex"><a href="https://quentinbruyere.sites.3wa.io/Soutenance/Projet_Final/codex">Codex</a></li>
                </ul>
            </nav>
            <a class="menu__sideModal__account" 
            <?php
            
            if(isset($_SESSION["connected"]) && $_SESSION["connected"]){
                echo 'href="https://quentinbruyere.sites.3wa.io/Soutenance/Projet_Final/account"';
            }else{
                echo 'href="https://quentinbruyere.sites.3wa.io/Soutenance/Projet_Final/authenticate"';
            }
            
            ?>
            >Account</a>
            <a class="menu__sideModal__aboutUs" href="https://quentinbruyere.sites.3wa.io/Soutenance/Projet_Final/about">About</a>
        </div>
        <a class="menu__homeBtn" href="https://quentinbruyere.sites.3wa.io/Soutenance/Projet_Final/"><img src="./assets/medias/imgs/Logo-WWW-Mae.png"></a>
        <div class="header__account">
            <a title="Account" 
            <?php
            
            if(isset($_SESSION["connected"]) && $_SESSION["connected"]){
                echo 'href="https://quentinbruyere.sites.3wa.io/Soutenance/Projet_Final/account"';
            }else{
                echo 'href="https://quentinbruyere.sites.3wa.io/Soutenance/Projet_Final/authenticate"';
            }
            
            ?>
            >
                <img src="./assets/medias/icons/account-48<?php 
                    if(isset($_SESSION["connected"]) && $_SESSION["connected"]){
                        echo "-green";
                    }
                ?>.png">
            </a>
        </div>
    </header>
    
    <?php 
        
        $path = substr($path, 1);
        
        require $path . "_template.phtml";
    
    ?>
    <footer>
        <div class="footerMenu">
            <nav>
                <ul>
                    <li><a href="https://quentinbruyere.sites.3wa.io/Soutenance/Projet_Final/about">About</a></li>
                    <li><a href="https://quentinbruyere.sites.3wa.io/Soutenance/Projet_Final/contact">Contact</a></li>
                </ul>
            </nav>
        </div>
        <p>Icons by <a target="_blank" href="https://icons8.com">Icons8</a></p>
    </footer>
    <script type="text/javascript" src="./assets/javascript/modules/sideMenuModal.js"></script>
</body>
</html>