<form method="POST" class="signUpForm">
    <label for="username">Username</label>
    <input type="text" name="username" class="signUpUsername"/>
    <label for="email">Email</label>
    <input type="email" name="email" class="signUpEmail"/>
    <label for="password">Password</label>
    <input type="password" name="password" class="signUpPassword"/>
    <input type="submit" value="Sign Up" class="signUpButton"/>
</form>