<form method="POST">
    <input type="text" name="username" class="signInUsername"/>
    <input type="password" name="password" class="signInPassword"/>
    <input type="submit" value="Sign In" class="signInButton"/>
</form>
<!--<script type="text/javascript" src="./assets/javascript/signIn_controller.js"></script>-->
<!--action="https://quentinbruyere.sites.3wa.io/Soutenance/Projet_Final/sign-in"-->